language: python
sudo: required

os:
  - linux
  - osx


osx_image: xcode6.4

env:
  matrix:
    - TEST_STYLE=1
    - TEST_FUNCTIONALITY=1

python:
  - "2.7"
  - "3.5"

before_install
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
  - pip install cython
  - pip install pandas==0.19
  - pip install scipy
install:
  - python setup.py install

before_script:
  - pip install nose
  - pip install pep8
  - pip install pyyaml

script: 
  - ./test_umi_tools.sh
