language: python
sudo: required

env:
  matrix:
    - TEST_STYLE=1
    - TEST_FUNCTIONALITY=1

python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - pip install cython

install:
  - python setup.py install

before_script:
  - pip install nose
  - pip install pep8
  - pip install pyyaml

script: 
  - umi_tools --help
  - umi_tools extract --help
  - umi_tools dedup --help
  - ./test_umi_tools.sh
