language: python
sudo: required

env:
  matrix:
    - TEST_STYLE=1
    - TEST_FUNCTIONALITY=1

python:
  - "2.7"
  - "3.5"

before_install:
  - pip install cython
  - pip install pandas==0.19

install:
  - python setup.py install

before_script:
  - pip install nose
  - pip install pep8
  - pip install pyyaml

script: 
  - ./test_umi_tools.sh
