language: python
sudo: required

matrix:
    include:
        - os: osx
          language: generic
          env: TEST_HELP=1
        - os: linux
          sudo: required
          python: 2.7
          env: TEST_FUNCTIONALITY=1
        - os: linux
          sudo: required
          python: 3.5
          env: TEST_FUNCTIONALITY=1
        - os: linux
          sudo: required
          python: 3.5
          env: TEST_STYLE=1

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install freetype; fi
# required to identify the correct pip. Shameless copied from https://github.com/secdev/scapy/blob/master/.travis/install.sh
  - PIP=`which pip || (python --version 2>&1 | grep -q 'Python 2' && which pip2) || (python --version 2>&1 | grep -q 'Python 3' && which pip3)`
  - $PIP install cython
  - $PIP install pandas==0.19
  - $PIP install scipy
install:
  - python setup.py install

before_script:
  - $PIP install nose
  - $PIP install pep8
  - $PIP install pyyaml

script: 
  - ./test_umi_tools.sh
