language: python
sudo: required

matrix:
    include:
        - os: osx
          language: generic
          env: TEST_HELP=1
        - os: linux
          sudo: required
          python: 2.7
          env: TEST_FUNCTIONALITY=1
        - os: linux
          sudo: required
          python: 3.5
          env: TEST_FUNCTIONALITY=1
        - os: linux
          sudo: required
          python: 3.5
          env: TEST_STYLE=1

before_install:
  - bash .travis/before_install.sh

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python3 setup.py install ; else python setup.py install; fi

before_script:
  - bash .travis/before_script.sh

script: 
  - bash .travis/test_umi_tools.sh
