language: python
sudo: required

matrix:
    include:
        - os: linux
          sudo: required
          python: 3.6
          env: TEST_FUNCTIONALITY=1
        - os: linux
          sudo: required
          python: 3.6
          env: TEST_STYLE=1

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install freetype; fi
  - pip install cython
  - pip install pandas==0.19
  - pip install scipy
  - pip install matplotlib==2.2.3  # can remove once py2 support dropped
install:
  - python setup.py install

before_script:
  - pip install nose
  - pip install pep8
  - pip install pyyaml

script: 
  - ./test_umi_tools.sh
